# Generated by Django 4.2.7 on 2025-07-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_information', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
