# Generated by Django 4.2.7 on 2025-07-17 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_information', '0003_remove_category_parent_id_remove_question_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stamp',
        ),
        migrations.DeleteModel(
            name='UserStamp',
        ),
    ]
