# Generated by Django 4.2.7 on 2025-07-17 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_information', '0004_delete_stamp_delete_userstamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
